### ISSUE TITLE
Too many dependencies 

### ISSUE THREAD

**Issue by dolmen** [Thiht/transactor#1]
Too many dependencies referenced in go.mod.

It would be helpful to move the test suite to a separate Go module in the same repo. Go workspaces might be helpful for development.

**Comment by Thiht** [comment]
Yeah this is a frustrating problem with go.mod. All the dependencies are actually test-only dependencies, and they won't be pulled on `go get` or `go mod download`.

I'm not a fan of changing how the code (and tests) is structured to bypass a shortcoming of the official tooling, so I'd rather keep it this way and wait for updates on https://github.com/golang/go/issues/44743 or https://github.com/golang/go/issues/26955

(I don't close the issue yet because I'm still a bit torn on this)

**Comment by Thiht** [comment]
I changed my mind and did the split, having an empty root go.mod is great :D

**Comment by komuw** [comment]
An alternative would be to use a tool like https://github.com/komuw/ote.
